"""create tables

Revision ID: 1c00e4eb20d4
Revises: 
Create Date: 2024-05-18 14:24:21.685006

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c00e4eb20d4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zawgrip",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("img_url", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "grip_type",
            sa.Enum("TWO_HANDED", "ONE_HANDED", name="griptype"),
            nullable=True,
        ),
        sa.Column("damage_bonus", sa.Text(), nullable=True),
        sa.Column("base_speed", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_zawgrip_base_speed"), "zawgrip", ["base_speed"], unique=False
    )
    op.create_index(
        op.f("ix_zawgrip_created_at"), "zawgrip", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_zawgrip_damage_bonus"), "zawgrip", ["damage_bonus"], unique=False
    )
    op.create_index(
        op.f("ix_zawgrip_grip_type"), "zawgrip", ["grip_type"], unique=False
    )
    op.create_index(op.f("ix_zawgrip_id"), "zawgrip", ["id"], unique=True)
    op.create_index(op.f("ix_zawgrip_img_url"), "zawgrip", ["img_url"], unique=False)
    op.create_index(op.f("ix_zawgrip_name"), "zawgrip", ["name"], unique=True)
    op.create_index(
        op.f("ix_zawgrip_updated_at"), "zawgrip", ["updated_at"], unique=False
    )
    op.create_table(
        "zawlink",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("img_url", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("speed_bonus", sa.Text(), nullable=True),
        sa.Column("critical_chance", sa.Text(), nullable=True),
        sa.Column("status_chance", sa.Text(), nullable=True),
        sa.Column("damage_bonus", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_zawlink_created_at"), "zawlink", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_zawlink_critical_chance"), "zawlink", ["critical_chance"], unique=False
    )
    op.create_index(
        op.f("ix_zawlink_damage_bonus"), "zawlink", ["damage_bonus"], unique=False
    )
    op.create_index(op.f("ix_zawlink_id"), "zawlink", ["id"], unique=True)
    op.create_index(op.f("ix_zawlink_img_url"), "zawlink", ["img_url"], unique=False)
    op.create_index(op.f("ix_zawlink_name"), "zawlink", ["name"], unique=True)
    op.create_index(
        op.f("ix_zawlink_speed_bonus"), "zawlink", ["speed_bonus"], unique=False
    )
    op.create_index(
        op.f("ix_zawlink_status_chance"), "zawlink", ["status_chance"], unique=False
    )
    op.create_index(
        op.f("ix_zawlink_updated_at"), "zawlink", ["updated_at"], unique=False
    )
    op.create_table(
        "zawstrike",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("img_url", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "type_1h",
            sa.Enum(
                "DAGGER",
                "MACHETE",
                "RAPIER",
                "SCYTHE",
                "SWORD",
                "NIKANA",
                name="onehandedtype",
            ),
            nullable=True,
        ),
        sa.Column(
            "type_2h",
            sa.Enum("STAFF", "POLEARM", "HEAVY_BLADE", "HAMMER", name="twohandedtype"),
            nullable=True,
        ),
        sa.Column("base_damage", sa.Float(), nullable=True),
        sa.Column("speed", sa.Text(), nullable=True),
        sa.Column("critical_chance", sa.Text(), nullable=True),
        sa.Column("critical_multiplier", sa.Float(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("riven_disposition", sa.Float(), nullable=True),
        sa.Column("impact_damage", sa.Float(), nullable=True),
        sa.Column("puncture_damage", sa.Float(), nullable=True),
        sa.Column("slash_damage", sa.Float(), nullable=True),
        sa.Column("viral_damage", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_zawstrike_base_damage"), "zawstrike", ["base_damage"], unique=False
    )
    op.create_index(
        op.f("ix_zawstrike_created_at"), "zawstrike", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_zawstrike_critical_chance"),
        "zawstrike",
        ["critical_chance"],
        unique=False,
    )
    op.create_index(
        op.f("ix_zawstrike_critical_multiplier"),
        "zawstrike",
        ["critical_multiplier"],
        unique=False,
    )
    op.create_index(op.f("ix_zawstrike_id"), "zawstrike", ["id"], unique=True)
    op.create_index(
        op.f("ix_zawstrike_img_url"), "zawstrike", ["img_url"], unique=False
    )
    op.create_index(
        op.f("ix_zawstrike_impact_damage"), "zawstrike", ["impact_damage"], unique=False
    )
    op.create_index(op.f("ix_zawstrike_name"), "zawstrike", ["name"], unique=True)
    op.create_index(
        op.f("ix_zawstrike_puncture_damage"),
        "zawstrike",
        ["puncture_damage"],
        unique=False,
    )
    op.create_index(
        op.f("ix_zawstrike_riven_disposition"),
        "zawstrike",
        ["riven_disposition"],
        unique=False,
    )
    op.create_index(
        op.f("ix_zawstrike_slash_damage"), "zawstrike", ["slash_damage"], unique=False
    )
    op.create_index(op.f("ix_zawstrike_speed"), "zawstrike", ["speed"], unique=False)
    op.create_index(op.f("ix_zawstrike_status"), "zawstrike", ["status"], unique=False)
    op.create_index(
        op.f("ix_zawstrike_type_1h"), "zawstrike", ["type_1h"], unique=False
    )
    op.create_index(
        op.f("ix_zawstrike_type_2h"), "zawstrike", ["type_2h"], unique=False
    )
    op.create_index(
        op.f("ix_zawstrike_updated_at"), "zawstrike", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_zawstrike_viral_damage"), "zawstrike", ["viral_damage"], unique=False
    )
    op.create_table(
        "zaw",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("level", sa.Text(), nullable=True),
        sa.Column("gild", sa.Boolean(), nullable=True),
        sa.Column("link_id", sa.UUID(), nullable=True),
        sa.Column("grip_id", sa.UUID(), nullable=True),
        sa.Column("strike_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["grip_id"],
            ["zawgrip.id"],
        ),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["zawlink.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strike_id"],
            ["zawstrike.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_zaw_created_at"), "zaw", ["created_at"], unique=False)
    op.create_index(op.f("ix_zaw_gild"), "zaw", ["gild"], unique=False)
    op.create_index(op.f("ix_zaw_id"), "zaw", ["id"], unique=True)
    op.create_index(op.f("ix_zaw_level"), "zaw", ["level"], unique=False)
    op.create_index(op.f("ix_zaw_name"), "zaw", ["name"], unique=True)
    op.create_index(op.f("ix_zaw_updated_at"), "zaw", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_zaw_updated_at"), table_name="zaw")
    op.drop_index(op.f("ix_zaw_name"), table_name="zaw")
    op.drop_index(op.f("ix_zaw_level"), table_name="zaw")
    op.drop_index(op.f("ix_zaw_id"), table_name="zaw")
    op.drop_index(op.f("ix_zaw_gild"), table_name="zaw")
    op.drop_index(op.f("ix_zaw_created_at"), table_name="zaw")
    op.drop_table("zaw")
    op.drop_index(op.f("ix_zawstrike_viral_damage"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_updated_at"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_type_2h"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_type_1h"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_status"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_speed"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_slash_damage"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_riven_disposition"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_puncture_damage"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_name"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_impact_damage"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_img_url"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_id"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_critical_multiplier"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_critical_chance"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_created_at"), table_name="zawstrike")
    op.drop_index(op.f("ix_zawstrike_base_damage"), table_name="zawstrike")
    op.drop_table("zawstrike")
    op.drop_index(op.f("ix_zawlink_updated_at"), table_name="zawlink")
    op.drop_index(op.f("ix_zawlink_status_chance"), table_name="zawlink")
    op.drop_index(op.f("ix_zawlink_speed_bonus"), table_name="zawlink")
    op.drop_index(op.f("ix_zawlink_name"), table_name="zawlink")
    op.drop_index(op.f("ix_zawlink_img_url"), table_name="zawlink")
    op.drop_index(op.f("ix_zawlink_id"), table_name="zawlink")
    op.drop_index(op.f("ix_zawlink_damage_bonus"), table_name="zawlink")
    op.drop_index(op.f("ix_zawlink_critical_chance"), table_name="zawlink")
    op.drop_index(op.f("ix_zawlink_created_at"), table_name="zawlink")
    op.drop_table("zawlink")
    op.drop_index(op.f("ix_zawgrip_updated_at"), table_name="zawgrip")
    op.drop_index(op.f("ix_zawgrip_name"), table_name="zawgrip")
    op.drop_index(op.f("ix_zawgrip_img_url"), table_name="zawgrip")
    op.drop_index(op.f("ix_zawgrip_id"), table_name="zawgrip")
    op.drop_index(op.f("ix_zawgrip_grip_type"), table_name="zawgrip")
    op.drop_index(op.f("ix_zawgrip_damage_bonus"), table_name="zawgrip")
    op.drop_index(op.f("ix_zawgrip_created_at"), table_name="zawgrip")
    op.drop_index(op.f("ix_zawgrip_base_speed"), table_name="zawgrip")
    op.drop_table("zawgrip")
    op.execute("DROP TYPE twohandedtype")
    op.execute("DROP TYPE onehandedtype")
    op.execute("DROP TYPE griptype")
    # ### end Alembic commands ###
